In [29]:
import pandas as pd
import numpy as np

In [27]:
df = pd.read_pickle('/data/gunsbrother/repos/CoMix/video_splits/D1_train.pkl')
df

,uid,participant_id,video_id,narration,start_timestamp,stop_timestamp,start_frame,stop_frame,verb,verb_class
0,12915,P08,P08_01,open fridge,00:00:04.09,00:00:05.84,245,350,open,2
1,12916,P08,P08_01,get milk,00:00:05.94,00:00:07.23,356,433,get,0
2,12917,P08,P08_01,close fridge,00:00:07.29,00:00:08.95,437,537,close,3
3,12918,P08,P08_01,get moka,00:00:10.64,00:00:13.50,638,810,get,0
4,12919,P08,P08_01,place water,00:00:15.72,00:00:21.14,943,1268,place,1
...,...,...,...,...,...,...,...,...,...,...
1538,15576,P08,P08_28,take bowl,00:00:21.40,00:00:22.79,1284,1367,take,0
1539,15577,P08,P08_28,open fridge,00:00:22.08,00:00:23.69,1324,1421,open,2
1540,15578,P08,P08_28,place bowl,00:00:23.04,00:00:25.13,1382,1507,place,1
1541,15579,P08,P08_28,close fridge,00:00:24.67,00:00:26.17,1480,1570,close,3
1542,15581,P08,P08_28,wipe hands,00:00:28.66,00:00:31.55,1719,1893,wipe,4

In [44]:
for id_domain in range(3):
    print(f'D{id_domain+1}')
    for split in ['train', 'test']:
        file_stem = f'D{id_domain+1}_{split}'
        df = pd.read_pickle(f'/data/gunsbrother/repos/CoMix/video_splits/{file_stem}.pkl')
        df['path'] = df['video_id']
        df['length'] = df['stop_frame'] - df['start_frame'] + 1
        df[['path', 'start_frame', 'length', 'verb_class']].to_csv(
            f'/data/gunsbrother/repos/haawron_mmaction2/data/_filelists/ek100/mm-sada_resampled/{file_stem}.txt',
            sep=' ', header=False, index=False)
        print(f'    {split:5s}: N = {len(df):4d}, T = {df["length"].sum()/3600:5.1f} h, K = {len(np.sort(df["verb_class"].unique()))}')

D1
    train: N = 1543, T =  91.3 h, K = 8
    test : N =  435, T =  23.9 h, K = 8
D2
    train: N = 2495, T = 145.8 h, K = 8
    test : N =  750, T =  40.3 h, K = 8
D3
    train: N = 3897, T = 144.0 h, K = 8
    test : N =  974, T =  36.4 h, K = 8

In [28]:
df = pd.read_pickle('/data/gunsbrother/repos/CoMix/video_splits/D1_test.pkl')
df

,uid,participant_id,video_id,narration,start_timestamp,stop_timestamp,start_frame,stop_frame,verb,verb_class
0,13744,P08,P08_09,get mocha pot,00:00:02.61,00:00:03.61,156,216,get,0
1,13747,P08,P08_09,clean mocha,00:00:09.66,00:00:10.16,579,609,clean,4
2,13748,P08,P08_09,pour water,00:00:10.26,00:00:12.19,615,731,pour,7
3,13749,P08,P08_09,get filter,00:00:14.11,00:00:15.61,846,936,get,0
4,13751,P08,P08_09,clean coffee filter,00:00:19.63,00:00:28.67,1177,1720,clean,4
...,...,...,...,...,...,...,...,...,...,...
430,14431,P08,P08_17,wipe off pan,00:09:27.87,00:09:30.48,34072,34228,wipe-off,4
431,14432,P08,P08_17,place pan,00:09:31.76,00:09:36.15,34305,34569,place,1
432,14433,P08,P08_17,close drawer,00:09:36.88,00:09:38.15,34612,34689,close,3
433,14434,P08,P08_17,close dishwasher,00:09:38.30,00:09:39.77,34698,34786,close,3
434,14435,P08,P08_17,wipe off hands,00:09:40.30,00:09:42.33,34818,34939,wipe-off,4